### ISSUE TITLE
rocon_app_manager_msgs: CMake error on message generation

### ISSUE THREAD

**Issue by jack-oquin** [robotics-in-concert/rocon_msgs#62] opened 2013-12-19 22:32 UTC
Several times lately, when updating my hydro-devel workspace and then rebuilding, I get a CMake failure like this:

```
-- +++ processing catkin package: 'rocon_app_manager_msgs'
-- ==> add_subdirectory(rocon_msgs/rocon_app_manager_msgs)
CMake Error at /home/joq/ros/wet/rocon/build/rocon_msgs/rocon_app_manager_msgs/cmake/rocon_app_manager_msgs-genmsg.cmake:3 (message):
  Could not find messages which
  '/home/joq/ros/wet/rocon/src/rocon_msgs/rocon_app_manager_msgs/msg/PairingClient.msg'
  depends on.  Did you forget to specify generate_messages(DEPENDENCIES ...)?

  Cannot locate message [KeyValue] in package [rocon_std_msgs] with paths
  [['/home/joq/ros/wet/scheduler/src/rocon_msgs/rocon_std_msgs/msg']]
Call Stack (most recent call first):
  /opt/ros/hydro/share/genmsg/cmake/genmsg-extras.cmake:288 (include)
  rocon_msgs/rocon_app_manager_msgs/CMakeLists.txt:41 (generate_messages)


-- Configuring incomplete, errors occurred!
make: *** [cmake_check_build_system] Error 1
```

**Comment by stonier** [comment] 2014-01-14 03:00
Can't reproduce this at all, nor can I find any problem in the cmake which might be triggering it.

This is only when you update right? Not on a clean source install? What do you do to get it working?

I'll leave it open and see if I run into the same problem at some point.

**Comment by jack-oquin** [comment] 2014-01-14 13:47
It has happened several times when rebuilding after an update. I have not done that recently, and no longer recall what I did to clear it. Probably, I deleted the build/ and devel/ trees and rebuilt everything from scratch.

I'll try to see if I can reproduce it with an update or a fresh install. If not, maybe we should just close this issue.

**Comment by stonier** [comment] 2014-04-16 11:08
Closing, as it's been a while...and things are much updated since then too.

**Closed as completed by stonier** 2014-04-16 11:08 UTC
Labels: bug
